"""initial schema

Revision ID: a9b6ce70a405
Revises: 
Create Date: 2026-07-20 13:48:19.559436
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import sentinelforge.core.db

revision: str = 'a9b6ce70a405'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_techniques',
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('tactics', sentinelforge.core.db.JSONBType(), nullable=False),
    sa.Column('is_subtechnique', sa.Boolean(), nullable=False),
    sa.Column('parent_technique_id', sa.String(length=20), nullable=True),
    sa.Column('platforms', sentinelforge.core.db.JSONBType(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('attack_version', sa.String(length=20), nullable=False),
    sa.Column('id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attack_techniques', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attack_techniques_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attack_techniques_parent_technique_id'), ['parent_technique_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attack_techniques_technique_id'), ['technique_id'], unique=True)

    op.create_table('revoked_tokens',
    sa.Column('jti', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sentinelforge.core.db.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('actor_id', sentinelforge.core.db.GUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('detail', sentinelforge.core.db.JSONBType(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sentinelforge.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_action', ['actor_id', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('coverage_snapshots',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('attack_version', sa.String(length=20), nullable=False),
    sa.Column('total_techniques', sa.Integer(), nullable=False),
    sa.Column('covered_count', sa.Integer(), nullable=False),
    sa.Column('partial_count', sa.Integer(), nullable=False),
    sa.Column('uncovered_count', sa.Integer(), nullable=False),
    sa.Column('detail', sentinelforge.core.db.JSONBType(), nullable=False),
    sa.Column('created_by_id', sentinelforge.core.db.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sentinelforge.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coverage_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coverage_snapshots_created_at'), ['created_at'], unique=False)

    op.create_table('detection_rules',
    sa.Column('sigma_id', sentinelforge.core.db.GUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('logsource_category', sa.String(length=100), nullable=True),
    sa.Column('logsource_product', sa.String(length=100), nullable=True),
    sa.Column('logsource_service', sa.String(length=100), nullable=True),
    sa.Column('tags', sentinelforge.core.db.JSONBType(), nullable=False),
    sa.Column('rule_references', sentinelforge.core.db.JSONBType(), nullable=False),
    sa.Column('falsepositives', sentinelforge.core.db.JSONBType(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('quality_breakdown', sentinelforge.core.db.JSONBType(), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('validation_issues', sentinelforge.core.db.JSONBType(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sentinelforge.core.db.GUID(), nullable=True),
    sa.Column('id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_rules_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index('ix_detection_rules_logsource', ['logsource_product', 'logsource_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_logsource_category'), ['logsource_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_logsource_product'), ['logsource_product'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_quality_score'), ['quality_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_sigma_id'), ['sigma_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_status'), ['status'], unique=False)
        batch_op.create_index('ix_detection_rules_status_severity', ['status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_validation_status'), ['validation_status'], unique=False)

    op.create_table('event_datasets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_format', sa.String(length=40), nullable=False),
    sa.Column('source_filename', sa.String(length=500), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('scenario_hint', sa.String(length=300), nullable=False),
    sa.Column('created_by_id', sentinelforge.core.db.GUID(), nullable=True),
    sa.Column('id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_datasets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_datasets_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_datasets_name'), ['name'], unique=True)

    op.create_table('incident_scenarios',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('dataset_id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['event_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_scenarios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_scenarios_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_scenarios_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_scenarios_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_scenarios_severity'), ['severity'], unique=False)

    op.create_table('normalized_events',
    sa.Column('dataset_id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('dest_ip', sa.String(length=45), nullable=True),
    sa.Column('process_name', sa.String(length=500), nullable=True),
    sa.Column('parent_process', sa.String(length=500), nullable=True),
    sa.Column('command_line', sa.Text(), nullable=True),
    sa.Column('event_id', sa.String(length=50), nullable=True),
    sa.Column('log_source', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('file_hash', sa.String(length=200), nullable=True),
    sa.Column('raw_event', sentinelforge.core.db.JSONBType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sentinelforge.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['event_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normalized_events', schema=None) as batch_op:
        batch_op.create_index('ix_normalized_events_dataset_sequence', ['dataset_id', 'sequence'], unique=False)
        batch_op.create_index('ix_normalized_events_dataset_timestamp', ['dataset_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_log_source'), ['log_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_process_name'), ['process_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_source_ip'), ['source_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_events_username'), ['username'], unique=False)

    op.create_table('rule_techniques',
    sa.Column('rule_id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('technique_id', sentinelforge.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['attack_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'technique_id')
    )
    op.create_table('rule_tests',
    sa.Column('rule_id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('dataset_id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('rule_version_number', sa.Integer(), nullable=False),
    sa.Column('expectation', sa.String(length=30), nullable=False),
    sa.Column('expected_match_count', sa.Integer(), nullable=True),
    sa.Column('events_processed', sa.Integer(), nullable=False),
    sa.Column('events_matched', sa.Integer(), nullable=False),
    sa.Column('execution_ms', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('result_label', sa.String(length=30), nullable=False),
    sa.Column('unresolved_fields', sentinelforge.core.db.JSONBType(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by_id', sentinelforge.core.db.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sentinelforge.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['event_datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_tests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_tests_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_tests_passed'), ['passed'], unique=False)
        batch_op.create_index('ix_rule_tests_rule_created', ['rule_id', 'created_at'], unique=False)

    op.create_table('rule_versions',
    sa.Column('rule_id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.String(length=500), nullable=False),
    sa.Column('created_by_id', sentinelforge.core.db.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sentinelforge.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version_number', name='uq_rule_version')
    )
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.create_index('ix_rule_versions_rule_version', ['rule_id', 'version_number'], unique=False)

    op.create_table('detection_matches',
    sa.Column('rule_test_id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('rule_id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('normalized_event_id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('matched_fields', sentinelforge.core.db.JSONBType(), nullable=False),
    sa.Column('explanation', sentinelforge.core.db.JSONBType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sentinelforge.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['normalized_event_id'], ['normalized_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_test_id'], ['rule_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_matches_normalized_event_id'), ['normalized_event_id'], unique=False)
        batch_op.create_index('ix_detection_matches_rule', ['rule_id'], unique=False)
        batch_op.create_index('ix_detection_matches_test_matched', ['rule_test_id', 'matched'], unique=False)

    op.create_table('incident_events',
    sa.Column('scenario_id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('normalized_event_id', sentinelforge.core.db.GUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('analyst_note', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sentinelforge.core.db.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['normalized_event_id'], ['normalized_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['incident_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_events_normalized_event_id'), ['normalized_event_id'], unique=False)
        batch_op.create_index('ix_incident_events_scenario_sequence', ['scenario_id', 'sequence'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_events_scenario_sequence')
        batch_op.drop_index(batch_op.f('ix_incident_events_normalized_event_id'))

    op.drop_table('incident_events')
    with op.batch_alter_table('detection_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_detection_matches_test_matched')
        batch_op.drop_index('ix_detection_matches_rule')
        batch_op.drop_index(batch_op.f('ix_detection_matches_normalized_event_id'))

    op.drop_table('detection_matches')
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_rule_versions_rule_version')

    op.drop_table('rule_versions')
    with op.batch_alter_table('rule_tests', schema=None) as batch_op:
        batch_op.drop_index('ix_rule_tests_rule_created')
        batch_op.drop_index(batch_op.f('ix_rule_tests_passed'))
        batch_op.drop_index(batch_op.f('ix_rule_tests_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_rule_tests_created_at'))

    op.drop_table('rule_tests')
    op.drop_table('rule_techniques')
    with op.batch_alter_table('normalized_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normalized_events_username'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_source_ip'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_process_name'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_log_source'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_host'))
        batch_op.drop_index(batch_op.f('ix_normalized_events_event_id'))
        batch_op.drop_index('ix_normalized_events_dataset_timestamp')
        batch_op.drop_index('ix_normalized_events_dataset_sequence')

    op.drop_table('normalized_events')
    with op.batch_alter_table('incident_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_scenarios_severity'))
        batch_op.drop_index(batch_op.f('ix_incident_scenarios_name'))
        batch_op.drop_index(batch_op.f('ix_incident_scenarios_is_demo'))
        batch_op.drop_index(batch_op.f('ix_incident_scenarios_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_incident_scenarios_created_at'))

    op.drop_table('incident_scenarios')
    with op.batch_alter_table('event_datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_datasets_name'))
        batch_op.drop_index(batch_op.f('ix_event_datasets_is_demo'))
        batch_op.drop_index(batch_op.f('ix_event_datasets_created_at'))

    op.drop_table('event_datasets')
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_rules_validation_status'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_title'))
        batch_op.drop_index('ix_detection_rules_status_severity')
        batch_op.drop_index(batch_op.f('ix_detection_rules_status'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_sigma_id'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_severity'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_quality_score'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_logsource_product'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_logsource_category'))
        batch_op.drop_index('ix_detection_rules_logsource')
        batch_op.drop_index(batch_op.f('ix_detection_rules_is_demo'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_created_at'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_archived_at'))

    op.drop_table('detection_rules')
    with op.batch_alter_table('coverage_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coverage_snapshots_created_at'))

    op.drop_table('coverage_snapshots')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('ix_audit_logs_actor_action')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_expires_at'))

    op.drop_table('revoked_tokens')
    with op.batch_alter_table('attack_techniques', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attack_techniques_technique_id'))
        batch_op.drop_index(batch_op.f('ix_attack_techniques_parent_technique_id'))
        batch_op.drop_index(batch_op.f('ix_attack_techniques_created_at'))

    op.drop_table('attack_techniques')
    # ### end Alembic commands ###
